In [55]:
import numpy as np

In [2]:
numpy

<module 'numpy' from '/opt/anaconda2/lib/python2.7/site-packages/numpy/__init__.pyc'>

In [3]:
lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]

In [4]:
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
type(lst)

list

In [8]:
arr = numpy.array(lst)

In [10]:
type(arr)

numpy.ndarray

In [24]:
zeros = numpy.zeros((20,10), dtype = int)

In [26]:
zeros.shape

(20, 10)

In [32]:
ones = numpy.ones((20,10), dtype = int)

In [42]:
numpy.random.random((3,3))

array([[0.49614242, 0.92223126, 0.57867238],
       [0.48151744, 0.372959  , 0.44604421],
       [0.16692707, 0.73951784, 0.47818625]])

In [46]:
numpy.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [51]:
for i in range(10):
    print(numpy.random.randint(1,10))

3
4
6
2
8
8
8
1
8
8


In [54]:
numpy.random.randint(1,10,(10,10))

array([[6, 5, 7, 4, 3, 3, 4, 3, 8, 9],
       [1, 4, 4, 4, 6, 3, 8, 7, 5, 1],
       [2, 4, 8, 4, 4, 8, 9, 1, 3, 8],
       [8, 1, 1, 9, 4, 5, 3, 8, 6, 5],
       [2, 8, 8, 6, 7, 3, 8, 3, 9, 7],
       [8, 6, 8, 4, 8, 2, 8, 4, 8, 7],
       [4, 3, 4, 6, 6, 3, 9, 3, 1, 9],
       [9, 7, 7, 5, 5, 9, 9, 2, 1, 6],
       [5, 7, 4, 1, 9, 9, 4, 9, 1, 4],
       [2, 1, 8, 4, 6, 5, 9, 4, 4, 7]])

In [56]:
np.random.randint(1,10)

9